package sv.edu.udb.www.entities;
// Generated 10-17-2021 06:48:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Autores generated by hbm2java
 */
@Entity
@Table(name="autores"
    ,catalog="inventario_libros"
)
public class Autores  implements java.io.Serializable {


     private String codigoAutor;
     private String nombreAutor;
     private String nacionalidad;
     private Set<Libros> libroses = new HashSet<Libros>(0);

    public Autores() {
    }

	
    public Autores(String codigoAutor, String nombreAutor, String nacionalidad) {
        this.codigoAutor = codigoAutor;
        this.nombreAutor = nombreAutor;
        this.nacionalidad = nacionalidad;
    }
    public Autores(String codigoAutor, String nombreAutor, String nacionalidad, Set<Libros> libroses) {
       this.codigoAutor = codigoAutor;
       this.nombreAutor = nombreAutor;
       this.nacionalidad = nacionalidad;
       this.libroses = libroses;
    }
   
     @Id 

    
    @Column(name="codigo_autor", unique=true, nullable=false, length=6)
    public String getCodigoAutor() {
        return this.codigoAutor;
    }
    
    public void setCodigoAutor(String codigoAutor) {
        this.codigoAutor = codigoAutor;
    }

    
    @Column(name="nombre_autor", nullable=false, length=50)
    public String getNombreAutor() {
        return this.nombreAutor;
    }
    
    public void setNombreAutor(String nombreAutor) {
        this.nombreAutor = nombreAutor;
    }

    
    @Column(name="nacionalidad", nullable=false, length=50)
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="autores")
    public Set<Libros> getLibroses() {
        return this.libroses;
    }
    
    public void setLibroses(Set<Libros> libroses) {
        this.libroses = libroses;
    }




}


