package sv.edu.udb.www.entities;
// Generated 10-17-2021 06:48:37 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Generos generated by hbm2java
 */
@Entity
@Table(name="generos"
    ,catalog="inventario_libros"
)
public class Generos  implements java.io.Serializable {


     private Integer idGenero;
     private String nombreGenero;
     private String descripcion;
     private Set<Libros> libroses = new HashSet<Libros>(0);

    public Generos() {
    }

	
    public Generos(String nombreGenero, String descripcion) {
        this.nombreGenero = nombreGenero;
        this.descripcion = descripcion;
    }
    public Generos(String nombreGenero, String descripcion, Set<Libros> libroses) {
       this.nombreGenero = nombreGenero;
       this.descripcion = descripcion;
       this.libroses = libroses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_genero", unique=true, nullable=false)
    public Integer getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }

    
    @Column(name="nombre_genero", nullable=false, length=40)
    public String getNombreGenero() {
        return this.nombreGenero;
    }
    
    public void setNombreGenero(String nombreGenero) {
        this.nombreGenero = nombreGenero;
    }

    
    @Column(name="descripcion", nullable=false, length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="generos")
    public Set<Libros> getLibroses() {
        return this.libroses;
    }
    
    public void setLibroses(Set<Libros> libroses) {
        this.libroses = libroses;
    }




}


